"""
server.py — HTTPS server for IRIS 2.0 Offline Module
Uses Python's built-in ThreadingHTTPServer + ssl — no Flask/Werkzeug dependency.

Endpoints
─────────
  GET /vision    → One-shot JSON snapshot  (poll every 0.5 s from the app)
  GET /events    → Server-Sent Events stream — pushes JSON every 0.5 s automatically
                   Best for mobile app: connect once, receive updates forever
  GET /stream    → MJPEG live video stream (browser / VLC)
  GET /health    → Quick liveness check

Mobile app — how to fetch:
  Polling  : GET https://<pi_ip>:5000/vision  every 500 ms
  SSE push : GET https://<pi_ip>:5000/events  (keep-alive; data arrives automatically)
             Each event line: data: {<json>}

TLS: self-signed cert generated by setup.sh.
     Mobile app must skip cert verification (self-signed) or install cert.pem as CA.
"""

import cv2
import json
import logging
import ssl
import threading
import time
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

try:
    _SSL_ERRORS = (BrokenPipeError, ConnectionResetError, ssl.SSLError, OSError)
except AttributeError:
    _SSL_ERRORS = (BrokenPipeError, ConnectionResetError, OSError)

from utils import SharedState, SensorFrame

log = logging.getLogger("iris.server")

BASE_DIR  = Path(__file__).parent
CERT_FILE = BASE_DIR / "cert.pem"
KEY_FILE  = BASE_DIR / "key.pem"

_start_time = time.time()


# ---------------------------------------------------------------------------
# Serialisation
# ---------------------------------------------------------------------------

def _iso_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds")


def _serialise(snap: SensorFrame) -> dict:
    return {
        "timestamp":      snap.timestamp or _iso_now(),
        "vision":         [
            {"name": d.name, "confidence": d.confidence}
            for d in snap.detections
        ],
        "distance_feet":  snap.distance_feet,
        "fall_detection": {
            "status":   snap.fall.status,
            "impact_g": round(snap.fall.impact_g, 3),
        },
        "system_status":  snap.system_status,
        "fps":            snap.fps,
        "errors":         snap.errors,
    }


# ---------------------------------------------------------------------------
# Request handler
# ---------------------------------------------------------------------------

class _Handler(BaseHTTPRequestHandler):
    """One instance per connection — ThreadingHTTPServer spawns a thread each time."""

    # Injected by ServerThread before the server starts
    state: SharedState = None

    def log_message(self, fmt, *args):
        log.debug("HTTP %s", fmt % args)

    def log_error(self, fmt, *args):
        log.warning("HTTP error: %s", fmt % args)

    def do_GET(self):
        path = self.path.split("?")[0]
        if   path == "/vision":  self._handle_vision()
        elif path == "/health":  self._handle_health()
        elif path == "/events":  self._handle_events()
        elif path == "/stream":  self._handle_stream()
        else:
            self._send_json({"error": "not found"}, status=404)

    # ── /vision — one-shot JSON ──────────────────────────────────────────────
    def _handle_vision(self):
        try:
            body = json.dumps(_serialise(self.state.snapshot()), ensure_ascii=False).encode()
            self.send_response(200)
            self.send_header("Content-Type",  "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(body)
        except Exception as exc:
            log.error("/vision error: %s", exc)
            self._send_json({"error": str(exc)}, status=500)

    # ── /health ──────────────────────────────────────────────────────────────
    def _handle_health(self):
        snap = self.state.snapshot()
        body = json.dumps({
            "status":        "ok",
            "system_status": snap.system_status,
            "fps":           snap.fps,
            "uptime_s":      round(time.time() - _start_time, 1),
        }).encode()
        self.send_response(200)
        self.send_header("Content-Type",  "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    # ── /events — Server-Sent Events (SSE) ───────────────────────────────────
    # Mobile app connects once; server pushes a JSON line every 0.5 s.
    # SSE format:   data: {<json>}\n\n
    # Reconnects automatically if the connection drops (built into SSE spec).
    def _handle_events(self):
        self.send_response(200)
        self.send_header("Content-Type",  "text/event-stream; charset=utf-8")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Connection",    "keep-alive")
        self.send_header("X-Accel-Buffering", "no")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        try:
            # initial keepalive comment so the client knows we're alive
            self.wfile.write(b": connected\n\n")
            self.wfile.flush()
        except Exception:
            return

        while not self.state.is_shutdown_requested():
            try:
                data = json.dumps(_serialise(self.state.snapshot()), ensure_ascii=False)
                self.wfile.write(f"data: {data}\n\n".encode("utf-8"))
                self.wfile.flush()
            except _SSL_ERRORS:
                break
            except Exception as exc:
                log.debug("/events write error: %s", exc)
                break
            time.sleep(0.5)

    # ── /stream — MJPEG video ────────────────────────────────────────────────
    def _handle_stream(self):
        self.send_response(200)
        # boundary=frame (no dashes) — body uses --frame as per MJPEG/MIME spec
        self.send_header("Content-Type",  "multipart/x-mixed-replace; boundary=frame")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()

        while not self.state.is_shutdown_requested():
            frame = self.state.get_annotated_frame()
            if frame is None:
                time.sleep(0.1)
                continue
            try:
                ok, buf = cv2.imencode(".jpg", frame, [cv2.IMWRITE_JPEG_QUALITY, 75])
                if not ok:
                    continue
                jpg = buf.tobytes()
                self.wfile.write(
                    b"--frame\r\n"
                    b"Content-Type: image/jpeg\r\n"
                    + f"Content-Length: {len(jpg)}\r\n\r\n".encode()
                    + jpg + b"\r\n"
                )
                self.wfile.flush()
            except _SSL_ERRORS:
                break
            except Exception as exc:
                log.debug("/stream error: %s", exc)
                break
            time.sleep(0.05)   # ~20 FPS cap

    # ── helper ───────────────────────────────────────────────────────────────
    def _send_json(self, data: dict, status: int = 200):
        body = json.dumps(data).encode()
        self.send_response(status)
        self.send_header("Content-Type",   "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


# ---------------------------------------------------------------------------
# Server thread
# ---------------------------------------------------------------------------

class ServerThread(threading.Thread):
    """
    Runs ThreadingHTTPServer + SSL in a daemon thread.
    Each incoming connection gets its own thread, so /events and /stream
    long-polls never block /vision or /health requests.
    """

    def __init__(
        self,
        state: SharedState,
        host: str = "0.0.0.0",
        port: int = 5000,
    ) -> None:
        super().__init__(name="ServerThread", daemon=True)
        self._state = state
        self._host  = host
        self._port  = port

    def run(self) -> None:
        log.info("ServerThread starting on %s:%d", self._host, self._port)

        # Inject shared state — must happen before the first request arrives
        _Handler.state = self._state

        # SO_REUSEADDR set on the class before bind() — prevents 'Address already in use'
        ThreadingHTTPServer.allow_reuse_address = True
        try:
            httpd = ThreadingHTTPServer((self._host, self._port), _Handler)
        except OSError as exc:
            log.critical(
                "Cannot bind port %d: %s  — run:  sudo fuser -k 5000/tcp  then restart.",
                self._port, exc,
            )
            self._state.add_error(f"Server bind failed: {exc}")
            return

        # Wrap socket with TLS
        if CERT_FILE.exists() and KEY_FILE.exists():
            ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
            ctx.load_cert_chain(certfile=str(CERT_FILE), keyfile=str(KEY_FILE))
            httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)
            proto = "https"
            log.info("TLS enabled — cert=%s", CERT_FILE)
        else:
            proto = "http"
            log.warning("cert.pem/key.pem not found — serving plain HTTP. Run setup.sh to fix.")

        log.info("IRIS server ready:")
        log.info("  JSON poll  : %s://%s:%d/vision",  proto, self._host, self._port)
        log.info("  SSE push   : %s://%s:%d/events",  proto, self._host, self._port)
        log.info("  Video      : %s://%s:%d/stream",  proto, self._host, self._port)
        log.info("  Health     : %s://%s:%d/health",  proto, self._host, self._port)

        try:
            httpd.serve_forever()
        except Exception as exc:
            log.critical("Server crashed: %s", exc)
            self._state.add_error(f"Server crash: {exc}")
        finally:
            httpd.server_close()
